# Generated by Django 5.2 on 2026-04-06 03:34

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AidRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("request_number", models.PositiveIntegerField(editable=False, unique=True)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("food", "Entrega de Comida"),
                            ("school", "Escuela"),
                            ("work", "Trabajo"),
                            ("medical_legal", "Visitas al Medico / Legales"),
                            ("other", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Type of Request",
                    ),
                ),
                ("date_needed", models.DateField(blank=True, null=True, verbose_name="Date Needed")),
                (
                    "additional_requests",
                    models.JSONField(blank=True, default=list, verbose_name="Additional Requests"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Anything else you want to tell us?", verbose_name="Notes"
                    ),
                ),
                (
                    "pickup_location",
                    models.CharField(blank=True, max_length=255, verbose_name="Pickup Location"),
                ),
                (
                    "pickup_neighborhood",
                    models.CharField(blank=True, max_length=100, verbose_name="Pickup Neighborhood"),
                ),
                (
                    "dropoff_location",
                    models.CharField(blank=True, max_length=255, verbose_name="Drop-off Location"),
                ),
                (
                    "dropoff_neighborhood",
                    models.CharField(blank=True, max_length=100, verbose_name="Drop-off Neighborhood"),
                ),
                ("is_round_trip", models.BooleanField(blank=True, null=True, verbose_name="Round Trip?")),
                ("is_recurring", models.BooleanField(blank=True, null=True, verbose_name="Recurring Ride?")),
                (
                    "recurring_schedule",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Monday–Friday, every Tuesday",
                        max_length=255,
                        verbose_name="Recurring Schedule",
                    ),
                ),
                (
                    "num_passengers",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Number of Passengers"
                    ),
                ),
                (
                    "time_preference",
                    models.CharField(blank=True, max_length=100, verbose_name="Preferred Time"),
                ),
                (
                    "delivery_neighborhood",
                    models.CharField(blank=True, max_length=100, verbose_name="Delivery Neighborhood"),
                ),
                (
                    "delivery_day_preference",
                    models.CharField(blank=True, max_length=100, verbose_name="Preferred Delivery Day"),
                ),
                (
                    "delivery_time_preference",
                    models.CharField(blank=True, max_length=100, verbose_name="Preferred Delivery Time"),
                ),
                ("diaper_sizes", models.CharField(blank=True, max_length=50, verbose_name="Diaper Sizes")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("dispatched", "Sent to Dispatch"),
                            ("childcare", "Sent to Childcare"),
                            ("follow_up", "Follow-up Needed"),
                            ("no_contact", "Unable to contact"),
                            ("complete", "Complete"),
                            ("urgent", "URGENT"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("contacted", models.BooleanField(default=False, verbose_name="Contacted?")),
                ("dispatcher_notes", models.TextField(blank=True, verbose_name="Dispatcher Notes")),
                (
                    "dispatch_status",
                    models.CharField(blank=True, max_length=100, verbose_name="Dispatch Status"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Updated")),
            ],
            options={
                "verbose_name": "Aid Request",
                "verbose_name_plural": "Aid Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Requester",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("phone_encrypted", models.BinaryField(blank=True, null=True)),
                ("phone_hash", models.TextField(blank=True, db_index=True)),
                ("signal_username_encrypted", models.BinaryField(blank=True, null=True)),
                ("has_signal", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Requester",
                "verbose_name_plural": "Requesters",
            },
        ),
        migrations.CreateModel(
            name="FoodRequest",
            fields=[],
            options={
                "verbose_name": "Food / Supply Request",
                "verbose_name_plural": "Food / Supply Requests",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("requests_app.aidrequest",),
        ),
        migrations.CreateModel(
            name="TransportRequest",
            fields=[],
            options={
                "verbose_name": "Transport Request",
                "verbose_name_plural": "Transport Requests",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("requests_app.aidrequest",),
        ),
        migrations.CreateModel(
            name="FormConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Config Name")),
                ("schema", models.JSONField(verbose_name="Form Schema")),
                ("is_active", models.BooleanField(default=False, verbose_name="Active?")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Form Configuration",
                "verbose_name_plural": "Form Configurations",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("is_active",),
                        name="unique_active_form_config",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HistoricalAidRequest",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("request_number", models.PositiveIntegerField(db_index=True, editable=False)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("food", "Entrega de Comida"),
                            ("school", "Escuela"),
                            ("work", "Trabajo"),
                            ("medical_legal", "Visitas al Medico / Legales"),
                            ("other", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Type of Request",
                    ),
                ),
                ("date_needed", models.DateField(blank=True, null=True, verbose_name="Date Needed")),
                (
                    "additional_requests",
                    models.JSONField(blank=True, default=list, verbose_name="Additional Requests"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Anything else you want to tell us?", verbose_name="Notes"
                    ),
                ),
                (
                    "pickup_location",
                    models.CharField(blank=True, max_length=255, verbose_name="Pickup Location"),
                ),
                (
                    "pickup_neighborhood",
                    models.CharField(blank=True, max_length=100, verbose_name="Pickup Neighborhood"),
                ),
                (
                    "dropoff_location",
                    models.CharField(blank=True, max_length=255, verbose_name="Drop-off Location"),
                ),
                (
                    "dropoff_neighborhood",
                    models.CharField(blank=True, max_length=100, verbose_name="Drop-off Neighborhood"),
                ),
                ("is_round_trip", models.BooleanField(blank=True, null=True, verbose_name="Round Trip?")),
                ("is_recurring", models.BooleanField(blank=True, null=True, verbose_name="Recurring Ride?")),
                (
                    "recurring_schedule",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Monday–Friday, every Tuesday",
                        max_length=255,
                        verbose_name="Recurring Schedule",
                    ),
                ),
                (
                    "num_passengers",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Number of Passengers"
                    ),
                ),
                (
                    "time_preference",
                    models.CharField(blank=True, max_length=100, verbose_name="Preferred Time"),
                ),
                (
                    "delivery_neighborhood",
                    models.CharField(blank=True, max_length=100, verbose_name="Delivery Neighborhood"),
                ),
                (
                    "delivery_day_preference",
                    models.CharField(blank=True, max_length=100, verbose_name="Preferred Delivery Day"),
                ),
                (
                    "delivery_time_preference",
                    models.CharField(blank=True, max_length=100, verbose_name="Preferred Delivery Time"),
                ),
                ("diaper_sizes", models.CharField(blank=True, max_length=50, verbose_name="Diaper Sizes")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("dispatched", "Sent to Dispatch"),
                            ("childcare", "Sent to Childcare"),
                            ("follow_up", "Follow-up Needed"),
                            ("no_contact", "Unable to contact"),
                            ("complete", "Complete"),
                            ("urgent", "URGENT"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("contacted", models.BooleanField(default=False, verbose_name="Contacted?")),
                ("dispatcher_notes", models.TextField(blank=True, verbose_name="Dispatcher Notes")),
                (
                    "dispatch_status",
                    models.CharField(blank=True, max_length=100, verbose_name="Dispatch Status"),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False, verbose_name="Created")),
                ("updated_at", models.DateTimeField(blank=True, editable=False, verbose_name="Last Updated")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="requests_app.requester",
                        verbose_name="Requester",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Aid Request",
                "verbose_name_plural": "historical Aid Requests",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name="aidrequest",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requests",
                to="requests_app.requester",
                verbose_name="Requester",
            ),
        ),
        migrations.AddIndex(
            model_name="aidrequest",
            index=models.Index(fields=["request_type", "status"], name="requests_ap_request_c66cff_idx"),
        ),
        migrations.AddIndex(
            model_name="aidrequest",
            index=models.Index(fields=["status"], name="requests_ap_status_6acc39_idx"),
        ),
        migrations.AddIndex(
            model_name="aidrequest",
            index=models.Index(fields=["-created_at"], name="requests_ap_created_bbded9_idx"),
        ),
    ]
