# Generated by Django 5.2 on 2026-04-06 16:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("requests_app", "0002_initial_formconfig"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aidrequest",
            options={
                "ordering": ["-created_at"],
                "permissions": [("can_export_pii", "Can export records with PII (phone, Signal username)")],
                "verbose_name": "Aid Request",
                "verbose_name_plural": "Aid Requests",
            },
        ),
    ]
