# Generated by Django 5.2 on 2026-04-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SecurityConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "deadman_enabled",
                    models.BooleanField(default=False, verbose_name="Dead Man Switch Enabled"),
                ),
                (
                    "deadman_warn_days",
                    models.PositiveIntegerField(
                        default=7, verbose_name="Warn after N days without admin login"
                    ),
                ),
                (
                    "deadman_wipe_days",
                    models.PositiveIntegerField(
                        default=14, verbose_name="Wipe after N days without admin login"
                    ),
                ),
                (
                    "remote_wipe_token_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 of the offline wipe token. Generate with: manage.py generate_wipe_token",
                        max_length=128,
                        verbose_name="Remote Wipe Token Hash",
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Configuration",
                "verbose_name_plural": "Security Configuration",
            },
        ),
    ]
